{
    "name": "PRB - Falabella Seller Center Integration",
    "version": "1.0.0",
    "category": "Sales",
    "summary": "Integración con Falabella Seller Center API",
    "author": "",
    "depends": ["base", "product", "sale"],
    "data": [
        "security/ir.model.access.csv",
        "data/falabella_cron.xml",
        "views/menu.xml",
        "views/falabella_account_views.xml",
        #"views/falabella_brand_views.xml",
        "views/falabella_order.xml",
        "views/product_template.xml",
        #"views/falabella_category.xml",
    ],
    "installable": True,
    "application": True,
}